### ISSUE TITLE
Missing module signature

### ISSUE THREAD

**Issue by darkoverlordofdata** [gasman/bonsai-c#7]
The spec at http://asmjs.org/spec/latest/ requires this module header format:

function MyAsmModule(stdlib, foreign, heap) {
    "use asm";
...

The pragma "use asm" is ignored by chrome, which is only guided by the signature to recognize this as a possible asmjs module. In any case, both Chrome and FF require this header signature.

There is also a minimum size requirement for the heap, my experiments showed me that I need at least 256k. When I conform to the spec, I see speed up of 2x in FF, and up to 10x in Chrome when testing the GeometricMean example in the spec.

I understand and totally agree with you about emscripten, but they drove the spec. And so you need a heap even if you don't use it...

**Comment by gasman** [comment]
Hi @darkoverlordofdata,

Bonsai-C does generate the `'use asm'` line (https://github.com/gasman/bonsai-c/blob/master/compiler.js#L784) - are you not seeing it in the output? If not, please provide details of the exact commands / source files you're using, so that I can try and reproduce this.

According to http://asmjs.org/spec/latest/#validatemodule-f, all of the `(stdlib, foreign, heap)` parameters are optional. I've just tested this against Firefox 47 - just in case Firefox's implementation is stricter than the spec requires - by running the testbed (https://github.com/gasman/bonsai-c/tree/master/testbed) with the following `module.js` file:

    function Module() {
        'use asm';
        function main() {
            var i = 41, temp = 0;
            if (((i = (temp = i) + 1 | 0, temp) | 0) > 41) {
                return 99;
            } else {
                return i | 0;
            }
            return 0;
        }
        return { main: main };

This outputs `Successfully compiled asm.js code (total compilation time 2ms; not stored in cache (too small to benefit))` in the console, indicating that Firefox accepts this as valid asm.js code.

As I understand it, Chrome does not formally support asm.js, although it might apply some optimisations to code written in an asm.js style. If so, I'd take the position that it's not bonsai-c's responsibility to generate optimal code on Chrome, as that defeats the whole point of asm.js being a formal spec. (To put it another way: if the Chrome project is not willing to provide a formal guarantee "if your code satisfies conditions XYZ, then Chrome will apply optimisations", then I don't think it's our job to try and reverse-engineer those precise conditions where Chrome's optimisation heuristics take effect. Life's too short... :-) )

**Comment by darkoverlordofdata** [comment]
I'm seeing the 'use asm' , but not the expected function signature in the module wrapper. My own experimentation & research tells me this is needed to get the full benefit
On the other hand, the only thing murkier than the spec is how chrome implements it.
Mostly, I wanted some confirmation on where your road map leads. I agree with your decisions, but I will go a different direction.
Thanks!
